### ISSUE TITLE
Indent characters overlay folded content

### ISSUE THREAD

**Issue by antonk52** [lukas-reineke/indent-blankline.nvim#118]
I've attached two screen shots for folded lines that are overlaid with the indent lines. A potential fix would be to disable the overlays for indented lines.

This is tested on the Lua branch.

Plugin enabled:
<img width="287" alt="Screen Shot 2021-06-07 at 00 51 34" src="https://user-images.githubusercontent.com/5817809/120941307-8a6ec080-c72a-11eb-928f-3bffa9852d60.png">

Plugin disabled:
<img width="256" alt="Screen Shot 2021-06-07 at 00 51 19" src="https://user-images.githubusercontent.com/5817809/120941310-8b9fed80-c72a-11eb-9e28-1c005fefdfeb.png">

**Comment by lukas-reineke** [comment]
:+1: Thanks for the issue.
I pushed a fix now. Foldtext should take priority over the indent guide.
In case someone does not want this, I also added an option `g:indent_blankline_show_foldtext` to turn it off, but it is on by default.

**Comment by antonk52** [comment]
Wow, thanks for a speedy replay!

I've pulled the commit but unfortunately the indent chars are still overlayed by fold characters. I will tinker with the setup to see if there's something off on my side. For reference here are the settings I'm using

<details><summary><code>nvim --version</code></summary>
<pre>
NVIM v0.5.0-dev+1311-gf8173df4d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1620559580505.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"</pre></details>

These are the plugin options that I use, I've tested with these  on and off:
```vim
let g:indent_blankline_char_list = ['|', '¦', '┆', '┊']
let g:indent_blankline_show_first_indent_level = v:false
let g:indent_blankline_show_trailing_blankline_indent = v:false
```

The HEAD plugin commit `841e31eafed8424d22bbf069eaccf8be86762009`(Lua branch)

**Comment by lukas-reineke** [comment]
Can you try to run `:IndentBlanklineRefresh` after you closed a fold?

**Comment by antonk52** [comment]
That works. Thanks! I guess ideally we could have an autogroup for toggling folds but it doesn't seem to exist 😅

**Comment by lukas-reineke** [comment]
Yeah.. there is no way to tell if a fold was opened or closed.

you can add `IndentBlanklineRefresh` to the keybindings you use to open and close folds, like `nnoremap zr zr:IndentBlanklineRefresh<CR>`
Or run `IndentBlanklineRefresh` on cursor moved
not ideal, but I can't think of a better way without a fold autocommand

**Comment by antonk52** [comment]
This should be added to the plugin documentation near the global option name since it was not quite obvious to figure out. Thank you for your help.

Feel free to close this issue

**Comment by lukas-reineke** [comment]
Added some more documentation

**Comment by akinsho** [comment]
@lukas-reineke having dug around for the opposite of this issue I decided to make a minor case for the default being inverted. In either case I found the solution so it's fine.

I guess it's more that it seems strange to me that by default if a person uses folds often they end up with multiple *patches* in their indentlines whereas in most other editors (I appreciate vim is often an exception) fold text wouldn't prevent indent characters from being shown.

I don't really have hard numbers for my case but I'm *guessing* that wanting indentlines to be consistent without holes throughout is probably the more common preference. Given the original basis for this plugin i.e. the blanklines and it's popularity.

FWIW this is what it looks like by default using this plugin without this option.

<img width="614" alt="Screen Shot 2021-06-22 at 17 28 41" src="https://user-images.githubusercontent.com/22454918/122964568-4eb93500-d37f-11eb-97d9-f68dc77cb495.png">

I again guesstimate that most users would rather not have those no matter what. I think the option is valuable since it caters to both sides so it's not a huge deal.

Anyway just my 2 cents, fine with either direction just though it might be worth making the case.

**Comment by lukas-reineke** [comment]
I totally see your point. But this only applies in the case `foldtext` uses indentation.
And the default `foldtext()` function does not. So if a user doesn't set a custom `foldtext`, it would look broken.

Default with no `foldtext` set
![Screen Capture_select-area_20210623095006](https://user-images.githubusercontent.com/12900252/123018006-b8c9ec80-d408-11eb-8855-e3eb7a835a33.png)

And how it would look if I make indent lines take priority
![Screen Capture_select-area_20210623095032](https://user-images.githubusercontent.com/12900252/123018052-d1d29d80-d408-11eb-97ce-812f88d32765.png)

That's the reason I turned it off.
If you have a custom `foldtext` function that uses the indentation, it makes sense to make indent lines take priority.

**Comment by akinsho** [comment]
Ah @lukas-reineke that's fair enough, I thought the default fold text had the hyphens but the text was indented by them. As you say that looks more broken. Thanks for clarifying.
