### ISSUE TITLE
CursorMoved for current context not triggering

### ISSUE THREAD

**Issue by sQVe** [lukas-reineke/indent-blankline.nvim#131]
Hey 👋🏼,

I'm trying to use the `lua` branch and the `g:indent_blankline_show_current_context` option but the **context** isn't updating correctly when I move my cursor. This is the full config I'm using:

```lua
--  ╻┏┓╻╺┳┓┏━╸┏┓╻╺┳╸   ┏┓ ╻  ┏━┓┏┓╻╻┏ ╻  ╻┏┓╻┏━╸
--  ┃┃┗┫ ┃┃┣╸ ┃┗┫ ┃    ┣┻┓┃  ┣━┫┃┗┫┣┻┓┃  ┃┃┗┫┣╸
--  ╹╹ ╹╺┻┛┗━╸╹ ╹ ╹    ┗━┛┗━╸╹ ╹╹ ╹╹ ╹┗━╸╹╹ ╹┗━╸
return function()
    vim.g.indent_blankline_char = "│"
    vim.g.indent_blankline_filetype_exclude = {"dashboard", "help", "packer"}
    vim.g.indent_blankline_show_current_context = true
    vim.g.indent_blankline_context_patterns = {
        "^for", "^if", "^object", "^table", "^while", "arguments", "block",
        "catch_clause", "class", "else_clause", "function", "if_statement",
        "import_statement", "jsx_element", "jsx_element",
        "jsx_self_closing_element", "method", "operation_type", "return",
        "try_statement"
    }
    vim.g.indent_blankline_use_treesitter = true
end
```

Strangely the context does update when the cursor is moved by scrolling. Attaching image for context.

![image](https://user-images.githubusercontent.com/2284724/123595053-bbee1f80-d7f0-11eb-99c2-165c0d2ce053.png)

**Comment by lukas-reineke** [comment]
Are you lazy loading the plugin? There seems to be an issue with packer #63
The problem is that when the plugin gets loaded, your variables are not set yet. The `CursorMoved` autocommand is set dynamically only when `g:indent_blankline_show_current_context` is on.

All you really need is an autocommand to run `IndentBlanklineRefresh` on `CursorMoved`. You could add this in your config instead.

```vim
augroup IndentBlanklineContextAutogroup
    autocmd!
    autocmd CursorMoved * IndentBlanklineRefresh
augroup END
```

Scrolling works because the plugin listens on `WinScrolled` regardless if context is on or not.

**Comment by sQVe** [comment]
👋

Yeah, I'm lazy loading the plugin. I figured that is was something related to it that. I'll add the autocmd.

Thank you for quick response and all your work on this plugin 🙏

**Comment by sQVe** [comment]
@lukas-reineke Yes, verified working with an `autocmd` or setting up variables under `setup` with `packer` 👍🏼 

Closing this! 🎉
