### ISSUE TITLE
Incorrect Indent guides

### ISSUE THREAD

**Issue by moshiur-raj** [lukas-reineke/indent-blankline.nvim#153]
![image](https://user-images.githubusercontent.com/36466700/126648179-4c1a925f-3c22-4998-8e63-ed9c500b2ed7.png)

1. Indents shown on empty line (line2). This only happens after having only one #include. If I have two or more #include <header.h> this problem does not occur.
2. Indents shown for space even after setting `vim.g.indent_blankline_strict_tabs = true`(line 4). This only happens for function arguments for some reason.

**Comment by lukas-reineke** [comment]
I can't reproduce 1. Do you maybe have whitespace on that line?

For 2, this is currently a limitation of how `strict_tabs` works. If there is no tab in the line at all, it uses spaces to calculate the indentation.
It should probably not do this. I'll have to think about if fixing this breaks anything else.

**Comment by moshiur-raj** [comment]
1 happens when `vim.g.indent_blankline_use_treesitter = true` is set.

**Comment by lukas-reineke** [comment]
> 1 happens when vim.g.indent_blankline_use_treesitter = true is set.

Then it is an issue in the treesitter C grammar. You can open an issue there https://github.com/tree-sitter/tree-sitter-c

**Comment by dccsillag** [comment]
Maybe I should open a new issue, but I guess this still fits into this one.

A similar issue often happens when using indent guides for Haskell code -- see the image.

![image](https://user-images.githubusercontent.com/15617291/128443501-5f24189b-0d2d-451b-bb56-3e58f1e91b1c.png)

The only non-default settings here are `g:indent_blankline_char`, `g:indent_blankline_buftype_exclude` and `g:indent_blankline_show_trailing_blankline_indent = v:false`.

I believe this happens because this plugin simply places an indentation guide every `&shiftwidth` columns. But, as the image shows, this is not enough for typical Haskell indentation, since it can start at basically any column.

Perhaps we could look into placing the indent guide on the first non-whitespace column above? Or maybe somehow use tree-sitter to try to solve this? (note: using `g:indent_blankline_use_treesitter = 1` didn't solve this, as I understand all it does is highlight the current indentation level).

Note that solving this non-uniform indentation probelm would also solve the second case presented above even when using only spaces.
