### ISSUE TITLE
indent marks and highlights on blanklines and context highlight doesn't change

### ISSUE THREAD

**Issue by ayushnix** [lukas-reineke/indent-blankline.nvim#172]
I'm seeing indent characters on blank lines and block highlights instead of simple line highlights. Also, the context highlight doesn't change at all. It just stays at the first level no matter where I am in the code.

Is this intended behavior? Here's neovim with treesitter and indent-blankline

https://user-images.githubusercontent.com/79408161/129454740-413297b3-f3d2-4e0d-92ef-8113baf0a31e.mp4

Here's VSCode in contrast.

https://user-images.githubusercontent.com/79408161/129454749-6c2a60d1-6e08-4e44-a61c-9e52216fb6c8.mp4

**Comment by lukas-reineke** [comment]
The first issue you are having, the weird highlight on blanklines, is a bug in Neovim. There is an issue open for indent-blankline here #59, which has a workaround to fix it for now.

The second issue, that the context doesn't update, is because you have to set the patterns that you want to see.
Take a look at `:help g:indent_blankline_context_patterns`
For your example, you probably want to add `for` and `^if`.
