### ISSUE TITLE
Weird indentation characters. How to disable them?

### ISSUE THREAD

**Issue by Pocco81** [lukas-reineke/indent-blankline.nvim#195]
I just updated the plugin and these thing are appearing:

![image](https://user-images.githubusercontent.com/58336662/131775850-2f7b1686-4ccd-4d72-abc5-7217f91cbdbe.png)

AFAIK this was introduced since/by this commit: bc35145af2e2a4874fc39e42c885c73d5cfc88e8. Everything was working fine before (a702f809ce85b16a83c44016bf10fe5a5765e98d):

![image](https://user-images.githubusercontent.com/58336662/131775950-2d48cc36-b6b9-4b1e-870a-e7c143057c6d.png)

Is this bug or is it "the new normal"? In case this was intended, is there a way to disable this?

**Comment by lukas-reineke** [comment]
This is now the correct behavior.
It displays what it would display without indent-blankline installed.
To change this, you need to set `listchars`. Either `tab` or `space`, depending on what you are using. `:help lcs-tab` `:help lcs-space` (or `:help lcs-space`)

**Comment by Pocco81** [comment]
> It displays what it would display without indent-blankline installed.

Why? Shouldn't overriding the `listchars` be the expected behavior? If I want to see the fillchars then I'd uninstall indent-blankline and vice-versa.

**Comment by Daxtorim** [comment]
Because without showing the characters defined in `listchars` there is no way to tell what the leading whitespace looks like. If the original file uses spaces and now you come in and use tabs, you leave behind an absolute mess without even knowing about it.

As you can also see in your screenshot above, this plugin *will* override characters at the indentation level with your defined character. The reason why it isn't doing it at the first level is becuase you set `vim.g.indent_blankline_show_first_indent_level = false`. This value would default to `true` otherwise.

**Comment by aperum** [comment]
I was also surprised by the new behavior. I'd expect listchars showing only if list is set.
I have a key to toggle list/nolist if i want to check my whitespaces. The current behavior of showing listchars even when list is not set seems counter intuitive to me.

**Comment by Daxtorim** [comment]
> I'd expect listchars showing only if list is set.

Truel, I guess. I have `set list` in my .vimrc and basically never turn it off. I didn't really consider how other people interact with this option.

I addressed this in #203.
