### ISSUE TITLE
Is it possible to only draw the current context indent line?

### ISSUE THREAD

**Issue by sthendev** [lukas-reineke/indent-blankline.nvim#269]
I use a transparent terminal and I would like the indent line to only appear only for the current context
![image](https://user-images.githubusercontent.com/37766610/137890734-68346a25-9cd7-415a-9c76-00621cf7156c.png)
I realize my life would be easier if I just had a background - I could set the foreground and background the same as my terminal background. Happy to try implement this myself with a point in the right direction :)

**Comment by sthendev** [comment]
This seems to have gotten what I want working. Not sure if there was already a better way. Keen to be educated :)
https://github.com/lukas-reineke/indent-blankline.nvim/pull/270

**Comment by lukas-reineke** [comment]
I am happy to add support for this :+1: 

Thank you for the PR, but that solution doesn't cover everything.
This plugin displays the underlining listchars when there is no indent guide, so just replacing it with `" "` is not good enough.

But once #255 is merged, it should actually be pretty easy to implement.
Instead of adding a `show_current_context_only` option, the indent character for the context should be its own option.
Then you can set the normal char to `""` and the context char to something else.

There needs to be `indent_blankline_context_char` which defaults to `indent_blankline_char` and `indent_blankline_context_char_list` which defaults to `nil`. If you want to, you can try to update your PR.
If not, I will implement it when I have some time.
