### ISSUE TITLE
instructions unclear

### ISSUE THREAD

**Issue by nschloe** [lukas-reineke/indent-blankline.nvim#294]
I just wanted to try out indent-blankline.nvim, but couldn't get it to work. I added
```
Plug 'lukas-reineke/indent-blankline.nvim'
```
to the Plug section of my `init.vim`, `PlugInstall`ed it, but I don't see any indentation guides. Do I _have_ to configure it? I added
```vim
require("indent_blankline").setup {
    char = "|",
    buftype_exclude = {"terminal"}
}
```
to `init.vim`, but apparently that's not the correct place. I'm a bit lost.

**Comment by lukas-reineke** [comment]
> Do I have to configure it?

No, it should just work. Can you check if the commands are available? Try to run `:IndentBlanklineRefresh` and see if it gives you an error.

> I added ... to init.vim

This is lua code. You can add it to your `init.vim` file as well, but you have to wrap it.

```vim
lua << EOF
require("indent_blankline").setup {
    char = "|",
    buftype_exclude = {"terminal"}
}
EOF
```

But again, the plugin should work out of the box with no configuration.

**Comment by nschloe** [comment]
> Can you check if the commands are available? Try to run :IndentBlanklineRefresh and see if it gives you an error.

```
E492: Not an editor command: IndentBlanklineRefresh
```

**Comment by lukas-reineke** [comment]
Okay, this means the plugin is not installed.
Try to run `:PlugInstall` again and check that `lukas-reineke/indent-blankline.nvim` is actually in the list of plugins that get installed.

**Comment by nschloe** [comment]
I get
```
:PlugInstall
```
```
- indent-blankline.nvim: Already installed
```
here.

**Comment by lukas-reineke** [comment]
That looks correct.
Have you restarted Neovim after installing?

**Comment by nschloe** [comment]
> Have you restarted Neovim after installing?

Sure, tried everything from restart to reinstall.

I know it's a weird issue that'll be hard to debug; let's not spend too much time on this. You can close it, and should I ever find a solution in the future, I'll post it here.

Thanks for the support!

**Comment by lukas-reineke** [comment]
It shouldn't be that hard to debug.
The commands will be available as soon as the plugin loads. Because they are not, the plugin is not loaded.
Packer says it's installed, so the only thing that is left is that the folder packer installed it to is not in your `runtimepath` in Neovim.

You can check what it is set to with `:set runtimepath`

It would also help if you can share your config, then I can maybe reproduce and debug it myself.

**Comment by lukas-reineke** [comment]
That all looks okay.

What is the output of `:version`?

**Comment by nschloe** [comment]
Upgraded to 0.5.1; it works now.

**Comment by nschloe** [comment]
Aha, I see in the README:

> This plugin requires Neovim 0.5 or higher.

Perhaps this could be checked at runtime?

**Comment by lukas-reineke** [comment]
:+1: yeah you need 0.5 or higher.

This is checked at runtime, but the plugin just exits silently if the version doesn't match.
Pretty much all (neo)vim plugins do it this way to be more portable. Instead of having a bunch of errors on startup, things that are not supported are just turned off.  
One could argue this is less of a concern for Neovim, but I don't think I want to change it.

**Comment by nschloe** [comment]
Alright, let's keep it like this. Thanks again for the support!

**Comment by dinhmai74** [comment]
I got the same issue with nvim 0.6. Just update indent-blankline tot the Version [2.10.2](https://github.com/lukas-reineke/indent-blankline.nvim/releases/tag/v2.10.2). and it crashed (Worked fine with nvim 0.6 in the early release version). @lukas-reineke

**Comment by inevity** [comment]
Use nvim 0.7, also E492: Not an editor command: IndentBlanklineRefresh
