### ISSUE TITLE
Support for Tab based indentation

### ISSUE THREAD

**Issue by ratheesh** [lukas-reineke/indent-blankline.nvim#3]
Will this support tab based indented source files? If not, is there a plan to support the feature?

**Comment by lukas-reineke** [comment]
Tabs should work fine.

This screenshot uses these settings

```
set listchars=eol:↴
set listchars+=tab:>-

let g:indent_blankline_space_char = '-'
let g:indent_blankline_char = '>'
```

![DeepinScreenshot_select-area_20200414012032](https://user-images.githubusercontent.com/12900252/79137818-62b5ee00-7dee-11ea-9c49-2464f66cba34.png)

Line 3, 5 and 8 are empty.

Let me know if you have any problems.

**Comment by Melkster** [comment]
@lukas-reineke Is it possible to not show the first indent level when using tabs like `g:indent_blankline_show_first_indent_level = v:false` does for spaces?

**Comment by lukas-reineke** [comment]
`g:indent_blankline_show_first_indent_level` works for tabs as well.

**Comment by Melkster** [comment]
@lukas-reineke Oh you're right, that's my bad. I had this line left in my config which made it appear as if the option wasn't working:

```vim
set list listchars=tab:▏\ 
```

**Comment by unphased** [comment]
So 97% of code I edit is space indented, but I'd like to be able to tell at a glance when code has tabs. My listchars is `vim.opt.listchars = "tab:→ ,extends:»,precedes:«,trail:·,nbsp:◆"`

What happens with indent-blankline configured as

```
safeRequire("indent_blankline").setup({
  char = "▏",
```

is that the first char of my tab list (`→`) is replaced with the `▏` which is totally reasonable but this means that it becomes impossible to tell whether the indent is done with a tab or spaces since the second tab listchar is space. 

Any ideas? Do you think we would require code change to allow indent-blankline to be able to get out of the way when a tab is used?

**Comment by lukas-reineke** [comment]
You can set a different character for tab in version 3. Please wait until it is released, or try it out with the `v3` branch.

**Comment by unphased** [comment]
That's spectacular news thank you.

**Comment by unphased** [comment]
@lukas-reineke v3 is *_wild_*! It can correctly apply indent markers for differently indented regions in the same file! Holy crap...
