### ISSUE TITLE
Cursor blinking isn't visible when its on one of the intend lines, is this normal ?

### ISSUE THREAD

**Issue by Dulanjala007** [lukas-reineke/indent-blankline.nvim#332]
when you go to insert mode, the cursor blinking (blue colored) isn't visible, so i don't know where the cursor is when it overlapped with one of the indent line...
why is this happening? any solutions?

**Comment by Dulanjala007** [comment]
fix was setting, guicursor to have a color highlight, not inherit the color of the position

**Comment by josecastillolema** [comment]
Can you please share the fix @Dulanjala007 ?

**Comment by webdevcat-me** [comment]
I encountered this issue, also. When my insert-mode I-cursor was over an indent line highlighted with the `IblIndent` highlight group, the cursor stayed visible. But whenever the cursor was over an indent line highlighted with `IblScope`, it changed to the same fg color as the indent line.

I think the reason for this is because for my setup, the indent highlight color is too close to my background color, and my Alacritty terminal's 'color contrast' feature kicks in and doesn't repaint the cursor to the highlight group's fg color. Whereas, the scope highlight fg color is just bright enough in comparison to my background to not trigger that feature, hence the cursor fg color gets painted to the same color as the indent line. And since the insert I-beam and the indent line character are the same shape, they become indistinguishable.

For now, my solution is to set the `IblScope` fg color to a value that is dark enough to trigger my terminal's color contrast feature, and thereby avoid painting the cursor to the same fg color as the 'scope' indent line.

Relevant bit of my `init.lua` file:

```lua
local hooks = require('ibl.hooks')

hooks.register(hooks.type.HIGHLIGHT_SETUP, function()
  vim.api.nvim_set_hl(0, "IblScope", {fg = '#454545'})
end)

require('ibl').setup({})
```
