### ISSUE TITLE
Hard to see cursor when hovering over indented space

### ISSUE THREAD

**Issue by BoilingSoup** [lukas-reineke/indent-blankline.nvim#346]
With indent-blankline enabled
![image](https://user-images.githubusercontent.com/84747244/148264104-7485943f-b63d-44d1-90c4-995b9dd48e05.png)

With indent-blankline disabled
![image](https://user-images.githubusercontent.com/84747244/148264217-f6c44f84-f804-4a11-b8a5-122cef232d32.png)

Not sure if this is related more to neovim's virtual text or the plugin. 
Is there a way to configure the cursor so it's more visible?

**Comment by lukas-reineke** [comment]
It is neither indent-blankline.nvim nor virtual text. The cursor just uses the foreground color of whatever character you are on.

You can change the cursor highlight with `:help hl-Cursor` or with your terminal.

**Comment by BoilingSoup** [comment]
thanks I was able to change it through my terminal emulator's settings

**Comment by timoleistner** [comment]
For anyone having the same issue like I had (Cursor wasnt visible at all when on indentation symbol) -> try turning off guicursor.
`set guicursor=`
or in lua:
`vim.opt.guicursor=""`

**Comment by jqhr** [comment]
@timoleistner it doesn't work

**Comment by jqhr** [comment]
@BoilingSoup I use indentLine, this plugin doesn't no have this problem.
The reason was terminal's cursor cell color feature. For alacritty, it was CellForeground and CellBackground. Alacritty change cursor's color like this.
![图片](https://user-images.githubusercontent.com/23305067/154179345-f02d6954-b07b-4205-95e5-eb7866661819.png)
The cursor's background color change to red and foreground color change to themes' default background color.
Will you fix this bug?Please

**Comment by lukas-reineke** [comment]
Again, this is not a bug in indent-blankline. This is the setting of your terminal / how you configured the cursor in Neovim.
There is nothing I can do in the plugin to change this.
