### ISSUE TITLE
context indent highlighted doesn't work on tsx files?

### ISSUE THREAD

**Issue by Glitches** [lukas-reineke/indent-blankline.nvim#349]
HI, I'm following the example of section "With context indent highlighted by treesitter" and is working as expexted in typescript files, while in tsx files all but the context highlight is working.
I'm on noevim 6.1.3 and lunarvim stable on it.
I trying to understand if it's my config bugged or maybe there's a problem in this plugin..

**Comment by lukas-reineke** [comment]
By default, there are not many context patterns defined. I didn't want to maintain a huge list of patterns, because they are different for each language.
There is already an issue about this #271 You can take a look there for some example configuration.

It is not very user-friendly, I will probably just end up supporting a bigger list by default.

**Comment by Glitches** [comment]
Gotcha! Thanks!
