### ISSUE TITLE
Use 'Comment' color for IndentBlacklineChar color

### ISSUE THREAD

**Issue by Andy3153** [lukas-reineke/indent-blankline.nvim#401]
So, reading through `:h indent-blankline.txt`, I noticed that, in order to change the color of the lines, I need to run:

```viml
highlight IndentBlanklineChar guifg=#00FF00 gui=nocombine
```

But, I would like to be able to make it use the color of the `Comment` highlight. Also, I noticed the helpfile says that, by default, it `takes guifg color from 'Whitespace'`, so, that means it is possible.

How can I feed it the color of the `Comment` highlight? Also, how can I include this in my nvim config file?

**Comment by lukas-reineke** [comment]
Normally you can just do `highlight link Foo Bar` to link 2 highlight groups together, so they are both the same.

But in this case it is more complicated. To work properly, the `IndentBlanklineChar` highlight group needs to have `gui=nocombine`. And `Comment` for example does not have that.  
You have to define your own highlight group to set this.

You can get the color value out of a highlight group, and then use that to create a new one. That is what I do for the default value. It gets the color from `Whitespace`.
But this requires some code.

You can take a look at the implementation here

https://github.com/lukas-reineke/indent-blankline.nvim/blob/347e3358e3ebf5ce18baf15d960d01eca5e42c6f/lua/indent_blankline/utils.lua#L205-L251

**Comment by lukas-reineke** [comment]
Yeah, like I said, you shouldn't use `link`, because it doesn't have the `gui=nocombine` option. If you don't have that, the indent guides inherit style options from the surrounding code. So for example, if a section of the code is italic, the indent guides will also become italic.

To do this properly, you'll have to write your own function that takes the `Comment` color and creates a new color group. Using `im.fn.hlID`, `vim.fn.synIDtrans`, etc. Similar to how the plugin does it.
