### ISSUE TITLE
Error messages when start on `startify`

### ISSUE THREAD

**Issue by tan-wei** [lukas-reineke/indent-blankline.nvim#448]
neovim complains:
```
indent-blanline: Invalid buffer id: 2
```
And now is on `startify` just after launch neovim.
Version: 42fe62eb8792e427b2c7b0e1fa1b0d9597baac89

**Comment by tan-wei** [comment]
So the message is shown just after I run `PlugUpdate`.

**Comment by lukas-reineke** [comment]
I don't use startify, not sure what it does to cause this. Sounds like a race condition somewhere.

This error was probably always there, and you can ignore it. The only change I did is to use `vim.notify` instead of a custom logger.
This should still be a debug message, but `vim.notify` by default displays all messages.

**Comment by tan-wei** [comment]
Got it. Sounds the message is not important.
