### ISSUE TITLE
[Bug] `IndentBlanklineEnable` doesn't respect `setup.filetype_exclude` and `setup.buftype_exclude`.

### ISSUE THREAD

**Issue by nyngwang** [lukas-reineke/indent-blankline.nvim#511]
As title. While the doc did say that `IndentBlanklineEnable` will overwrite include/exclude, I sometimes need to temporarily disable this plugin due to the lagging issue on large projects. It will be great if these commands `IndentBlanklineEnable/Disable` can respect those `filetype/buftype_exclude` in the `setup`.

**Comment by lukas-reineke** [comment]
This is not a bug. Like the docs say, this is expected behavior.

`IndentBlanklineEnable` is buffer specific. If you don't want indent-blankline enabled for a buffer, just don't run the command for that buffer.
If you want to disable / enable it globally, use the commands with bang (!) `IndentBlanklineEnable!` this will respect include / exclude.
