### ISSUE TITLE
Opening cpp file gives error E5560

### ISSUE THREAD

**Issue by jjiangweilan** [lukas-reineke/indent-blankline.nvim#515]
![image](https://user-images.githubusercontent.com/13493742/209039161-7bb17a3e-2ab7-4090-98ff-5da246d13d06.png)
I updated the plugin recently and received this error. This error doesn't occur if I open other files, only cpp files. And it only occurs in the first time I open any cpp file. Can anyone help

**Comment by lukas-reineke** [comment]
The original error would have been `Spawning language server with cmd: "%s" failed`. So you need to check your config why the LSP for cpp files can't start.

That it can't echo the error correctly seems to be a bug with Neovim. But the stacktrace is not very clear, it's hard to tell where the problem is.

**Comment by jjiangweilan** [comment]
i will track it deeper. I found it's not a problem specific to indent-blank line. thanks!
