### ISSUE TITLE
Comments not included in context

### ISSUE THREAD

**Issue by LandonSchropp** [lukas-reineke/indent-blankline.nvim#521]
Apologies if this is already a known limitation, but I couldn't find it in the documentation or the issues.

When highlighting the current context, comments don't seem to be included.

Could this be due to the treesitter parsing? Is there any way to resolve it?

https://user-images.githubusercontent.com/361591/210286997-decace1c-2c2c-49a9-a3bd-d117521e8663.mov

**Comment by iHnR** [comment]
I've been having this as well so I did some digging. 
[The relevant code](https://github.com/lukas-reineke/indent-blankline.nvim/blob/7075d7861f7a6bbf0de0298c83f8a13195e6ec01/lua/indent_blankline/utils.lua#L212-L223) seems fine. This also happens when `use_treesitter_scope` is `true` so I'm guessing it's a treesitter limitation.
It's weird since treesitter seems to parse the parents/scope of comments correctly.

**Comment by iHnR** [comment]
I did some more testing by defining the following function in my config:
```lua
-- debugging
Test_ts = function()
  -- hello
  local ts_utils_status, ts_utils = pcall(require, "nvim-treesitter.ts_utils")
  local cursor_node = ts_utils.get_node_at_cursor()
  local parent_node = cursor_node:parent()
  vim.notify(parent_node:type())
end
```
Calling `:lua Test_ts()` works fine most of the time but fails when the cursor is on a comment. If you change the function to show the type of the current node, it returns `source` rather than `comment`.
It seems this issue is specific to the lua api of treesitter as the treesitter api for python does not have this limitation.

**Comment by iHnR** [comment]
This can be resolved by changing `local cursor_node = ts_utils.get_node_at_cursor()` [here](https://github.com/lukas-reineke/indent-blankline.nvim/blob/7075d7861f7a6bbf0de0298c83f8a13195e6ec01/lua/indent_blankline/utils.lua#L198C24-L198C24) to `local cursor_node = vim.treesitter.get_node()`. The latter api correctly identifies comments.

**Comment by lukas-reineke** [comment]
Fixed in version 3
