### ISSUE TITLE
Show current context stops working when cursor is on code, but works when on space char

### ISSUE THREAD

**Issue by elC0mpa** [lukas-reineke/indent-blankline.nvim#539]
I think this shouldn't work like in the video. The question is:
Is this the correct behavior? I want current context to be always visible for the same line of code

[Screencast from 2023-02-09 16-05-03.webm](https://user-images.githubusercontent.com/53531665/217939288-f09caca8-d25c-45e8-bc0f-fee0c8f751f5.webm)

Here you have my config

```
vim.opt.termguicolors = true
vim.opt.list = true
vim.opt.listchars:append "space:⋅"

require("indent_blankline").setup {
     enabled = true,
     show_current_context = true,
     char = "|",
     char_blankline = '┆',
     use_treesitter = true,
     context_char = '*',
     use_treesitter_scope = true,
}
```

**Comment by lukas-reineke** [comment]
This is what treesitter returns as the current scope.
I agree, the implementation for Javascript isn't that great. But this is not something I can fix here, this comes from [use_treesitter_scope](https://github.com/nvim-treesitter/nvim-treesitter)

**Comment by elC0mpa** [comment]
I understand, now let me understand something
Which would be the advantages of using tree sitter with blank line?
I am asking because after your answer I remove the treesitter keys from config and now it shows the context correctly, but I suppose this should have some disadvantage
```
require("indent_blankline").setup {
     enabled = true,
     show_current_context = true,
     char = "|",
     char_blankline = '┆',
     use_treesitter = false,
     context_char = '*',
     use_treesitter_scope = false,
}
```

**Comment by lukas-reineke** [comment]
The first one `use_treesitter` is for calculating the indentation of blank lines.
If you have it off, there is a simple logic built into indent-blankline. It basically takes the indentation of the next none blank line.
If you have it on, it uses treesitter to get the indentation.

Treesitter can do smarter things here, like reducing the indentation after a function has returned. But treesitter indentation is still very buggy in some languages. I hope this gets better with time, but I personally have this off.

The other one `use_treesitter_scope` is only for the context. Context always uses treesitter, the only difference is that by default it just walks up the node tree until it finds a type that matches defined in `:help g:indent_blankline_context_patterns`.
I built it this way because at the time there was no scope. But now, treesitter has a built-in concept of the current scope. This takes into account how different languages handle scope and hoisting.
With `use_treesitter_scope` on, you use that instead. I personally have this on and much prefer it over the old pattern matching way. It is not just eye candy that highlights the current indent, it actually visualizes the scope based on the language you are in. Which in some languages like Javascript and Python is really helpful, because they do weird stuff with the scope.

For example, in Python an if block is not a new scope, so you can define a variable in an if block and use it outside. The scope in this case is the whole function.
![2023-02-15_09-57](https://user-images.githubusercontent.com/12900252/218898428-4fdd9af3-d1f2-4cec-81ce-f301879c827c.png)

Rust is designed better, so the if block is its own scope
![2023-02-15_10-05](https://user-images.githubusercontent.com/12900252/218898664-e746b073-d452-4c69-a5f1-1849ebbad752.png)

But it is not perfect as well. There are edge cases that are not handled as nice in some language.
In the end, use whatever works better for you.

**Comment by elC0mpa** [comment]
Thank you very much for this great answer @lukas-reineke. Really appreciate it!
