### ISSUE TITLE
Buggy extra_indent_level = -1: lines begin and end where the next level should

### ISSUE THREAD

**Issue by alnj** [lukas-reineke/indent-blankline.nvim#55]
As you can see on this screenshot, although the last indent level is indeed hidden, the other indent lines' beginning and end are determined as if they were the next indent level.

I'm using the today's Neovim release (NVIM v0.5.0-dev+1126-g0496b572a), indent-blankline.nvim's lua branch, and the only settings are my line character and the extra indent level at -1.
![1615112392](https://user-images.githubusercontent.com/1331748/110236847-6d163480-7f38-11eb-8b45-877d52b9de26.png)

**Comment by lukas-reineke** [comment]
`g:indent_blankline_extra_indent_level` doesn't really make sense anymore. I added this initially because it was easy, but the only reason for it to exists is to not show the trailing blankline indent (which is why its broken now that we do all indents).
I think I will just remove it.

I have already added a new option to not show the trailing indent for blanklines.
You can use `let g:indent_blankline_show_trailing_blankline_indent = v:false` to get the same result as `let g:indent_blankline_extra_indent_level = -1` now.

**Comment by alnj** [comment]
Beautiful, thanks. I'll leave the issue open if you want it as a reminder to remove the old option.
