### ISSUE TITLE
Dynamic highlight groups

### ISSUE THREAD

**Issue by tranzystorek-io** [lukas-reineke/indent-blankline.nvim#602]
I am interested in contributing a feature that lets IB determine the highlight group dynamically based on information from the rainbow delimiters plugin.

Related discussion: https://gitlab.com/HiPhish/rainbow-delimiters.nvim/-/issues/6

In short, I'd like to obtain the highlight group based on the parentheses/braces nesting level instead of the indentation level.
I was trying to find a place in code where we could optionally plug a call to rainbow-delimiters, but I'm not sure.

I'll apreciate any pointers or comments!

**Comment by lukas-reineke** [comment]
I am working on a new version for indent-blankline that will let other plugins hook into the generation of indentation guides.

But that being said, integrating rainbow-delimiters will be very difficult. The 2 plugins fundamentally work totally different.

**Comment by tranzystorek-io** [comment]
Can you shortly describe where that fundamental difference lies? Is it the indentation level vs delimiter nesting level?

**Comment by lukas-reineke** [comment]
Both `indent-blankline` and `rainbow-delimiters` use treesitter. But the nodes are not the same. You would need some kind of logic that can map between the two. Writing this logic would be very difficult, and probably unique for each language, because each language has a different treesitter grammar.

Take a look at what rainbow-delimiters is doing now, https://gitlab.com/HiPhish/rainbow-delimiters.nvim/-/tree/master/queries it has queries for each possible bracket, for each language. You would then need to write logic to map each of those, to anything an indent-blankline scope could be, which is _a lot_.

And you can't just compare the start and end, because treesitter nodes usually contain the whole statement. For example, in this go code, `rainbow-delimiters` would have a node for `{` and one for `}`, but `indent-blankline`s scope is the whole thing, including the `if err...`

```go
if err != nil {
	// some code
}
```

**Comment by tranzystorek-io** [comment]
Thank you for taking the time to write this!

Indeed, this looks more complicated when comparing what parts of the treesitter structure these plugins operate on.

I don't want to immediately give up on the idea, especially since both IB and RD don't really seem to work for competing use-cases, but I'd probably need to study treesitter a bit more before I can put together some proposal.

**Comment by HiPhish** [comment]
To add to the discussion, the node that contains the delimiters is captured as `@container`. In the above Go code that node would be the `block` node of this tree:

```
if_statement [0, 0] - [2, 1]
  "if" [0, 0] - [0, 2]
  condition: binary_expression [0, 3] - [0, 13]
    left: identifier [0, 3] - [0, 6]
    operator: "!=" [0, 7] - [0, 9]
    right: nil [0, 10] - [0, 13]
  consequence: block [0, 14] - [2, 1]
    "{" [0, 14] - [0, 15]
    comment [1, 1] - [1, 13]
      "text" [1, 1] - [1, 2]
        "/" [1, 1] - [1, 2]
      "text" [1, 2] - [1, 3]
        "/" [1, 2] - [1, 3]
      "text" [1, 4] - [1, 8]
      "text" [1, 9] - [1, 13]
    "}" [2, 0] - [2, 1]
"\n" [2, 1] - [3, 0]
```

So it is possible to get the containers, but I don't know how you would map them to "indentation". But assuming we could do something with the container nodes, how would we get to them in the first place? For this I would use a custom strategy and builds a tree of container nodes and stores it somewhere, for example in a `b:` variable. Or it could feed the values directly to indent blankline. This strategy could be a wrapper that can wrap around another strategy so we don't have to re-invent highlighting all over again. I don't have such a strategy, but it should not be hard to write one. Open an issue in my repo if it would be useful.

**Comment by lukas-reineke** [comment]
This is now supported, see `:help hooks.builtin.scope_highlight_from_extmark`

**Comment by tranzystorek-io** [comment]
Thank you for working on this!
