### ISSUE TITLE
Indent is shown on one more level than it should be

### ISSUE THREAD

**Issue by CallumHoward** [lukas-reineke/indent-blankline.nvim#7]
<img width="252" alt="Screen Shot 2020-04-19 at 3 05 54 pm" src="https://user-images.githubusercontent.com/7144420/79680099-48956900-824f-11ea-9fa5-20ee2a2f8a52.png">

Expected behaviour is plugin only displays one indent guide for the file on line 10.

my config is:
```viml
let g:indentLine_char = '│'
let g:indentLine_color_term = 232
```

Using the latest available HEAD.

-- EDIT --
To clarify, whitespace characters are shown as `-` in the screenshot above. There are no spaces or tabs on line 5, 7, 13, 15.

**Comment by lukas-reineke** [comment]
Line 10 looks correct to me.

It shows indentation up to the same level as code.
Everything in the if block is indented 2 levels.

Line 5, 7, 13 etc show one indentation because everything in the main function is indented one level.

**Comment by CallumHoward** [comment]
Ah, I see now. I misunderstood the intended behaviour, I expected it to behave as it does in VSCode --which in this example would be identical to Yggdroot/indentLine except for one extra indent guide on line 10.

<img width="344" alt="Screen Shot 2020-04-19 at 7 59 55 pm" src="https://user-images.githubusercontent.com/7144420/79684935-6cb97000-8278-11ea-8081-7800f6e05545.png">

**Comment by CallumHoward** [comment]
...and now that I look closer at the example screenshot of VSCode above I see there is an indent guide from line 4 to 19, but it appears all the way to the left rather than 4 spaces indented.

**Comment by CallumHoward** [comment]
Hmm, I still think I'm not quite getting the behaviour demonstrated in the readme screenshots, in which the first indent guide is at column 0.

**Comment by lukas-reineke** [comment]
I see, VSCode does not show the last indentation. I think its weird, but it would be easy to add an option to support this. I'll look into that :+1: 

You can show indentation in the first column with:
`g:indentLine_showFirstIndentLevel = 1`
But it does not work for empty lines, because of this bug in Vim https://github.com/vim/vim/issues/4854

Once this is fixed, i'll add support for that as well.
For now you can set `listchar` `eol` to something so it doesn't look as bad. In the screenshots I used `set listchars=eol:↴`

**Comment by lukas-reineke** [comment]
I added `g:indent_blankline_extra_indent_level` now, this should let you make the indentation work the same as VSCode.

Just add this
`let g:indent_blankline_extra_indent_level = -1`

**Comment by CallumHoward** [comment]
Perfect, thank you!
