### ISSUE TITLE
Indent now showing as greater than character instead of pipe

### ISSUE THREAD

**Issue by badloop** [lukas-reineke/indent-blankline.nvim#702]
### Problem

At some point my indents have gone from being lines to showing the greater than character for each indent.  Nothing was updated in my config.  Using Lazy.nvim as package manager.

![image](https://github.com/lukas-reineke/indent-blankline.nvim/assets/10452840/3e4e6833-ca68-4ea8-b357-eba765e98d46)

### Steps to reproduce

Load using the above config.  Open neovim.  Create file that has indents.

### Expected behavior

Indent character would show as pipe

### Neovim version (nvim -v)

v0.10.0-dev

**Comment by Danielkonge** [comment]
Since you write `main = "ibl"`, I assume you are trying to use version 3, but what you write in `opts` doesn't make sense in the setup of v3. You either need to stick with a 2.something version or update your `opts` accordingly. 

A good start is to look here: https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3

**Comment by lukas-reineke** [comment]
In your screenshot, you are actually not using indent-blankline at all. If you have a `config` function in lazy, the setup function is not automatically called.
What you are seeing is just `:help listchars`

Like @Danielkonge said, please read the migration guide.
