### ISSUE TITLE
flickering when using nvim_set_current_line

### ISSUE THREAD

**Issue by Sam-programs** [lukas-reineke/indent-blankline.nvim#755]
### Problem

i have a cmp auto-semicolon adder that uses `nvim_set_current_line`
which makes the indent-guides flicker whenever i use cmp

https://github.com/lukas-reineke/indent-blankline.nvim/assets/130783534/88de8613-5bcf-4b49-84b1-9364a9217da1

the only fix was migrating the semicolon adder to only use keys

### Steps to reproduce

```lua
require('ibl').setup()
local cmp = require('cmp')
cmp.setup()
local kind = cmp.lsp.CompletionItemKind
local semicolon_langs = {["c"] = true ,["cpp"] = true}
cmp.event:on('confirm_done', function(event)
   local entry = event.entry
   local item = entry:get_completion_item()
   local line = vim.api.nvim_get_current_line()
   local lastchar = line:sub(#line, #line)
   if lastchar ~= ';' and semicolon_langs[vim.o.filetype] then
      if item.kind == kind.Function or item.kind == kind.Method then
         vim.api.nvim_set_current_line(line .. ';')
      end
   end
end)
```

### Expected behavior

no flickering when `nvim_set_current_line` is called

### Neovim version (nvim -v)

v0.9.2

**Comment by lukas-reineke** [comment]
This is not a bug, if you replace the whole line, ibl just needs some time to render it again.
You can manually call `require("ibl").refresh(bufnr)` to refresh without debounce, that will probably help a bit. But I would recommend you use `:help nvim_buf_set_text()` instead of `nvim_set_current_line`, so you don't replace the whole line in the first place.

**Comment by Sam-programs** [comment]
yea that works thanks
