### ISSUE TITLE
Change background color from your example

### ISSUE THREAD

**Issue by horga83** [lukas-reineke/indent-blankline.nvim#841]
In your example on the github page you give this setup.  How would one change the foreground color?
I have tried to understand this but I am not a lua person.  Would you please help.  Thank you.

```
local highlight = {
    "CursorColumn",
    "Whitespace",
}
require("ibl").setup {
    indent = { highlight = highlight, char = "" },
    whitespace = {
        highlight = highlight,
        remove_blankline_trail = false,
    },
    scope = { enabled = false },
}
```

**Comment by horga83** [comment]
I figured this out, here is the answer:
```
return {
	"lukas-reineke/indent-blankline.nvim",
	main = "ibl",
	lazy = false,
	opts = {
    indent = { highlight = "VertSplit", char = "│" },
  },
}
```
And here is the stuff nobody seems to mention, "VertSpit" is a Vim code for character attributes.  At the Vim or Nvim command line if you type ":highlight<cr>", you will see a list of all the character attributes and colors.  Substitute "VertSplit" for whatever you like.
The char="|" by the way is a unicode character, go into insert mode, hit <ctrl-v>u2502 to insert it, if you want to see what code a unicode character is in Nvim, put your cursor on the character and hit ga.

I figured this out by fluke by looking at this code which gives a alternating space and shade for indent lines.
```
local highlight = {
    "CursorColumn",
     "Whitespace",
}

return {
  "lukas-reineke/indent-blankline.nvim",
  main = "ibl",
  lazy = false,

  opts = {
  indent = { highlight = highlight, char = "" },
     whitespace = {
        highlight = highlight,
        remove_blankline_trail = true,
     },
    scope = { enabled = true },
}
```
I discovered by chance that :highlight allowed one to look at the highlight attributes and I recalled seeing "CursorColumn" in the list.
Hope this helps everyone with some solid information.  Too much assumption these days in docs.

**Comment by lukas-reineke** [comment]
[There is an example in the readme that shows how to set custom highlight groups](https://github.com/lukas-reineke/indent-blankline.nvim?tab=readme-ov-file#multiple-indent-colors)

> Too much assumption these days in docs.

Did you read `:help ibl`? Everything is explained there in a lot more detail.

**Comment by horga83** [comment]
Hi and thank you for your comment.

I don't believe anywhere in :help ibl does it explain that if you type
:highlight in nvim it will display all the vars and their current
setting.  :h ibl is great but far too much info to get a simple setting
enabled.

A new user to VIM/NVIM would have no clue, this is why I explained my
example in detail.

I'm a firm believer in the math textbook principle, a complete example
goes a long way.

Many thanks for your plugin.

Cheers

**Comment by lukas-reineke** [comment]
> I don't believe anywhere in :help ibl does it explain that if you type
:highlight in nvim it will display all the vars and their current
setting.

True, that is because `:highlight` is not a command of IBL. It is a built-in Neovim command. 
It's not possible to explain every built-in command in the plugin doc again. They are already documented by Neovim itself.  

`:help ibl.config.indent.highlight` tells you it expects a highlight group, or a list of highlight groups. If you don't know what that is, you can just do `:help highlight-group`, or `:help highlight`.

You can also use `:help CTRL-]` on underlined text in the docs and jump to the definition.

There is also `:help :helpgrep` that lets you grep for documentation. And there are plugins that let you fuzzy search documentation with previews, like FZF and telescope.

The Neovim help docs are very good. It pays off getting good at using them.

> I'm a firm believer in the math textbook principle, a complete example
goes a long way.

I don't disagree. That's why there are multiple ready-made config examples in the README. And a lot of the settings have examples in the documentation.


I'm not saying IBLs documentation is perfect, it can always be better. I will add an explicit link to the highlight group docs from `ibl.config.whitespace.highlight`.  
But other than that, I'm not really sure what else I can realisticly improve.

**Comment by horga83** [comment]
Many thanks,

I appreciate your work on this and if there is anything else you can
think 
of that would help a new user that would be great.  

Your plugin was the very first one I tried, having never used Neovim
before, so 
you can imagine it is all a bit overwhelming.

Cheers
