### ISSUE TITLE
Split window and horizontal movement.

### ISSUE THREAD

**Issue by vallahor** [lukas-reineke/indent-blankline.nvim#920]
Splitting the window with the same buffer and having a line that doesn't fit in the window (nowrap) moving between them causes some rendering issues on the other side.

![issue](https://github.com/user-attachments/assets/2be6608d-01ff-431b-b95d-dc81e7a4abdf)

A simple solution was to add `virt_text_hide = true` in `vim.api.nvim_buf_set_extmark` at least it doesn't overwrite the text of the other windows.
I tried `vim.api.nvim__add_ns` but I was having to write a lot of code, it worked in parts but still writing to the same bufnr.

![issue_2](https://github.com/user-attachments/assets/3c1a5f8b-eaf3-474a-986c-df8311cd1012)

### Neovim version (nvim -v)

NVIM v0.10.1

**Comment by lukas-reineke** [comment]
It's a limitation of how virtual text in Neovim works. I don't know of a way to fix this.

`virt_text_hide` mitigates this problem a bit, but because all indent extmarks start on the first column, it also means that you lose all indentation once you horizontal scroll any buffer. That is worse in my opinion.

**Comment by vallahor** [comment]
oh ok! I got it, thanks!
